# Generated by Django 2.0.5 on 2018-08-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AQI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
